FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY opensearch_client.py .
COPY event_generator.py .
COPY simulators ./simulators

CMD ["python", "-u", "app.py"]